version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moleculer_db
      MYSQL_USER: root@localhost
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - moleculer_network

volumes:
  mysql-data:

networks:
  moleculer_network:
    driver: bridge
